# Generated by Django 5.2.15 on 2026-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='eligibility_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
