# Generated by Django 5.2.15 on 2026-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_chat_cached_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_gatekeeper',
            field=models.BooleanField(default=False),
        ),
    ]
